### ISSUE TITLE
Licenza GPLv2?

### ISSUE THREAD

**Issue by ViralAgency** [iocaller/CallCenterManagementSystem_prototipo#1]
Salve, sto dando un occhiata al vostro progetto, che trovo utile e ricco di documentazione. Ma ho alcune domande:

Vedo che c'è un file .jar compilato chiamato [mysql-connector-java-8.0.22](https://github.com/iocaller/CallCenterManagementSystem_prototipo/blob/main/GestioneCallCenter/mysql-connector-java-8.0.22.jar) che dovrebbe avere, stando alle mie risultanze, una licenza GPLv2, che si estenderebbe anche al vostro software. 
E' corretto?

Questo é anche il file di configurazione del database?

**Comment by iocaller** [comment]
Ciao, grazie per la segnalazione. Confermo quanto detto da te, ho provveduto tempestivamente ad inserire la licenza
